name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
          
      - name: Install dependencies
        run: |
          uv venv
          source .venv/bin/activate
          uv sync --all-extras
          
      - name: Install pre-commit
        run: |
          pip install pre-commit
          pre-commit install
          
      - name: Run pre-commit hooks
        run: pre-commit run --all-files
        
      - name: Run type checking
        run: |
          source .venv/bin/activate
          uv run pyright
          
      - name: Run tests
        run: |
          source .venv/bin/activate
          uv run pytest tests -v
