name: Generate Tool Specifications

on:
  release:
    types: [published]
  # Allow manual triggering of the workflow
  workflow_dispatch:

jobs:
  generate-specs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install 3.12.8

      - name: Install the project
        run: uv sync --dev --all-extras
      
      - name: Generate tool specifications
        run: python generate_tool_specs.py
      
      - name: Configure Git and add upstream
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote add upstream https://github.com/crewAIInc/crewAI.git
          git fetch upstream

      - name: Commit and push if changed
        run: |
          git add tool.specs.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update tool specifications for $(git describe --tags --abbrev=0)" && git push)
